version: '3.9'

services:
    postgres_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: ps_g5
            POSTGRES_PASSWORD: "1234"
        tmpfs:
            - /var/lib/postgresql/data
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    express:
        build: ./express
        volumes:
            - ./express/src:/app/src
        depends_on: 
            - postgres_db
            
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080